# Generated by Django 4.2.7 on 2024-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile_images/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/schedule_covers/'),
        ),
    ]
